### ISSUE TITLE
Juicy data for a graph on the dashboard page

### ISSUE THREAD

**Issue by timdenike** [mihasya/ishmael#13]
Some history for the dashboard would be good to answer the question "Did that query I fixed 3 hours ago actually make a dent?"

select sum(ts_cnt) as total_queries,(sum(query_time_sum)/sum(ts_cnt)) as avg_time, count(*) as distinct_queries,date_format(ts_max,"%m/%d/%y %H:00:00") as period from query_review_history_db182_XXXXX_mud group by period;    (Hourly resolution - might want to drop this to a 10 minute resolution?   Or add a where clause to keep the results within the scope of the report?)

Here's a daily rollup.  (date_format(ts_max,"%m/%d/%y 00:00:00"))
+---------------+------------------+------------------+-------------------+
| total_queries | avg_time         | distinct_queries | period            |
+---------------+------------------+------------------+-------------------+
|          2965 | 34.5442127871875 |              201 | 04/07/10 00:00:00 | 
|         20449 | 30.7374205208972 |             1175 | 04/08/10 00:00:00 | 
|         21635 | 36.6146623486924 |             1041 | 04/09/10 00:00:00 | 
|         18916 | 33.5940657913823 |             1025 | 04/10/10 00:00:00 | 
|         18837 | 35.6162684383353 |             1067 | 04/11/10 00:00:00 | 
|         19051 | 39.6365240836017 |             1033 | 04/12/10 00:00:00 | 
|         20296 | 35.9402833430608 |             1069 | 04/13/10 00:00:00 | 
|         21376 | 40.2324553749518 |              943 | 04/14/10 00:00:00 | 
|         21335 | 30.6335957241975 |             1128 | 04/15/10 00:00:00 | 
|         20323 | 18.3012299363094 |             1501 | 04/16/10 00:00:00 | 
|         16027 | 6.95505661425011 |             1875 | 04/17/10 00:00:00 | 
|         20605 | 27.1870738023926 |             1265 | 04/18/10 00:00:00 | 
|         21803 | 32.8136269002039 |             1159 | 04/19/10 00:00:00 | 
|         23022 | 34.4820856970364 |             1181 | 04/20/10 00:00:00 | 
|          5462 |    7.43459799817 |             1130 | 04/21/10 00:00:00 | 
+---------------+------------------+------------------+-------------------+
15 rows in set (0.07 sec)

T

**Comment by mihasya** [comment]
closed by 2a3a9bc58351e8e21f40e22643db6f3a9d867168: dashboard graph (avg query time / hour)
